### PR TITLE
[Utils]: Increase odds ratio resolution to 4 decimal points

### PR DESCRIPTION
**Pull request by carcruz**
Issue: opentargets/issues#2071
Deploy: https://deploy-preview-210--genetics-app.netlify.app/

### CODE REVIEW

**Comment by d0choa** [comment]
I know this might be a way the library works, but if possible it would be nice to resolve this rounding issue:

Screenshot 2022-03-09 at 14 46 36

It's not very consistent that we have different decimal points if the value is a '0.XXXX' or a '1.XXX'. We would ideally want both of them to have the same number of decimal points (e.g. 4).

**Review by LucaFumis — APPROVED** [review]
Thank you @carcruz - looks good

**Comment by carcruz** [comment]
@d0choa fix numbers to 4 digits in lastest commit 
Deploy: https://deploy-preview-210--genetics-app.netlify.app/

**Comment by d0choa** [comment]
Could you please increase the resolution for:

1 - Confidence intervals in the study table?
https://deploy-preview-210--genetics-app.netlify.app/study/GCST90038599

2- Odds ratio and confidence intervals for the GWAS lead variants in variant page:
https://deploy-preview-210--genetics-app.netlify.app/variant/9_97819742_A_G

3 - Odds ratio in the phewas table
https://deploy-preview-210--genetics-app.netlify.app/variant/9_97819742_A_G

**Pull request closed without merging**
